### PR TITLE
Add Color customization to work priorities

### PR DESCRIPTION
**Pull request by alextd**
Adds settings for colors for each Work Priority Level. 2-9 colors can be
defined and each level is assigned the next color. If the max priority
level is greater than the number of colors, the last two colors are
blended together for the remaining levels.

### CODE REVIEW

**Comment by alextd** [comment]
A bonus rewrite of Settings so it's not all static and so settings aren't list

I hoped this would make saving my color list cleaner, but it requires a copy list since it is set to null for some reason?

**Comment by alextd** [comment]
Oh snap, whenever I update my master, this pull request points to the new stuff. Oh well.

Another commit on a different thing - just changes the shown job priority to be the most common sub-priority, instead of the highest.

I found that I would have crafting at priority 3 but increased the medicine crafting to 1, it would show 1 even though most of the work is priority 3. So this changes has it show 3 instead.

**Comment by alextd** [comment]
Noticed it filtered out 0-priority tasks, and I thought this new method should include them. A job will show blank if most sub-jobs are blank - with the little asterisk showing there is an exception as before.

Also bugfix concerning Dictionary usage. TryGetValue doesn't mean "do or do not, there is no try", it means it avoids try/catch shenanigans. Terrible name I think.

**Comment by FluffierThanThou** [comment]
thanks for your contributions :) I've been rather busy lately, but I'll try and make some time to review them soon (tm).

**Comment by alextd** [comment]
Oh snap here I am again. I thought I saw this pull request closed so I pushed again. Tacking on another commit, I guess!

NEW STUFF - Incrementing a worktype now increments all the workgivers individually, instead of resetting them to the worktype's priority. There are a few minor concerns since wrapping is bounded by a range of priorities, and I wonder if that's not what someone would want so maybe it needs config options. There should also be review on the usage of GetPriority (more in the commit message)

**Pull request closed without merging**
